### ISSUE TITLE
Show count of stories on top right.

### ISSUE THREAD

**Issue by Swastikyadav** [Swastikyadav/hacker-news-clone#12]
- On top right show the number of stories currentlly in view.
- There is a state with array of stories.
- Length of that array should be enough to show the count of stories in view.

Roughly something like this.

![image](https://user-images.githubusercontent.com/44374494/192549089-cb22bebc-f312-43de-8274-66f90e7a2429.png)

**Comment by toddmcintire** [comment]
Would it be alright if I give this issue a shot?

**Comment by Swastikyadav** [comment]
> Would it be alright if I give this issue a shot?

Hi @toddmcintire,

Sure, I have assigned this issue to you. Please fork and raise PR against master of this repo.

**Comment by toddmcintire** [comment]
I haven't been able to get very far with this issue, its taking more React knowledge then I initially thought. If anyone else wants to attempt this issue while I research the proper ways to share data between components please be my guest!

**Comment by zaidsidd360** [comment]
Hey Swastik, could I work on this one?

**Comment by ranjandsingh** [comment]
@Swastikyadav Hey Can I do this ??

**Comment by Swastikyadav** [comment]
> Hey Swastik, could I work on this one?

Hey, @zaidsidd360,

Sure, please go ahead and work on this. Assigning this issue to you.

**Comment by zaidsidd360** [comment]
Hey @Swastikyadav , I've opened up a PR for this issue. Please check it out!
