### ISSUE TITLE
Change the `Past` button text to `Best`.

### ISSUE THREAD

**Issue by Swastikyadav** [Swastikyadav/hacker-news-clone#2]
- File path: `src/components/menu/menu.component.jsx` line 39
- Change the text `Past` to `Best`.

That tab is for the best hackerNews stories not specifically for the the past stories.

**Comment by Harsh97x** [comment]
I can do this one. Can you assign me?

**Comment by mustafaazad03** [comment]
Hi @Swastikyadav ,
I Have Read Your Issue and As Beginner I Want To Contribute To This Issue and I humbly wait for you to assign the task to me.

**Comment by Swastikyadav** [comment]
> I can do this one. Can you assign me?

@Harsh97x,
Thank you for your interest in this issue. This issue is now assigned to you. Please read the CONTRIBUTING.md file and raise a PR to be merged into master of this repo.

Please let me know if you face any doubt or blocker, I will be more than happy to help you out.

**Comment by Swastikyadav** [comment]
> Hi @Swastikyadav , I Have Read Your Issue and As Beginner I Want To Contribute To This Issue and I humbly wait for you to assign the task to me.

Hi @Mustafa-Azad025,
Thank you for you interest, I really appreciate it.

I have assigned this issue to Harsh, as he approached first.

But, you can take this issue #3. It is also a beginner issue. You just have to install antd npm package. Comment in that issue for any doubt.
