### ISSUE TITLE
Story with long metadata text not handled properly

### ISSUE THREAD

**Issue by athdromeda** [Swastikyadav/hacker-news-clone#22]
Some story with long metadata takes more spaces than another. Would you mind if I assigned to this issue and labeled this issue as hacktoberfest?

![Screenshot 2022-10-07 at 16-11-35 React App](https://user-images.githubusercontent.com/69031224/194521869-c66866db-2e3b-404f-a08d-03bd76a8739c.png)
<p align="center">Story with long metadata</p>
<br>

**Comment by Swastikyadav** [comment]
Hi @athdromeda 

Thanks for pointing this out. And sorry for the delay in response.

Yes, please take this issue forward by raising a PR with the fix. I think we can truncate all metadata to a certain length.

I have assigned this issue to you.
