### ISSUE TITLE
Add `antd` to package.json dependencies.

### ISSUE THREAD

**Issue by Swastikyadav** [Swastikyadav/hacker-news-clone#3]
- Install `Ant Design` npm package in the repo.
- It is required for features to be implemented in near future.

Here is the `antd` installation guide: https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization

**Comment by haseeb-xd** [comment]
i want to try solve this issue.

**Comment by Swastikyadav** [comment]
> i want to try solve this issue.

Welcome @haseeb-xd 

I have assigned you this issue. Please fork this repo, install antd package, and raise a PR against master of this repo.

For any query, help, or doubt please comment here. I will be available to help.

**Comment by roniardev** [comment]
is this issue has been resolved? if didn't i wanna contribute on this issue ASAP

**Comment by haseeb-xd** [comment]
Bro, i am waiting for hacktoberfest to start. Once it starts, i will make a PR.
