### ISSUE TITLE
Desktop view redesign.

### ISSUE THREAD

**Issue by Swastikyadav** [Swastikyadav/hacker-news-clone#9]
- The web app is designed with mobile first approach.
- Redesign the desktop view with media query.
- The basic design requirement is to have 3 cards in one row (Can be achieved easily with flexbox).
- The mobile view should remain same.
- For simplicity let's have only one break point which is `768px`.

Desired Output is something similar to this image:

![image](https://user-images.githubusercontent.com/44374494/192542424-00c76437-1233-4a73-82d4-0eaea5f19ab9.png)

**Comment by DugarRishab** [comment]
Hey @Swastikyadav I would like to work on this enhancement

**Comment by RohitRajvaidya5** [comment]
I want to contribute to this issue can you assign me on this?

**Comment by Swastikyadav** [comment]
> Hey @Swastikyadav I would like to work on this enhancement

Hey @DugarRishab,

Thank you for your interest. I have assigned you this issue. Please fork and clone the repo, make changes in your branch, and raise a PR (pull request) against the master of this branch.

**Comment by Swastikyadav** [comment]
> I want to contribute to this issue can you assign me on this?

Hi @RohitRajvaidya5,

Thanks for your interest, but this issue goes to Rishab, as he approached first. May you please look into other issues and see if any issue interests you.

**Comment by RohitRajvaidya5** [comment]
Sure.

**Comment by DugarRishab** [comment]
@Swastikyadav I have opened up a pull request for this issue. Please check it out.
